#!/bin/sh

GUNICORN=/usr/local/bin/gunicorn
ROOT=/path/to/project
PID=/var/run/gunicorn.pid

APP=main:application

rm -f $PID

cd $ROOT || exit
exec $GUNICORN -c $ROOT/gunicorn.conf.py --pid=$PID $APP
